#
#  Makefile for the kernel Sensor device drivers.
#

obj-$(CONFIG_SENSORS_CORE)		+= sensors_core.o
obj-$(CONFIG_GYRO_K3G)			+= k3g.o
obj-$(CONFIG_SENSORS_AK8975)	+= ak8975.o
obj-$(CONFIG_SENSORS_K3DH)		+= k3dh.o
obj-$(CONFIG_OPTICAL_BH1721)	+=bh1721.o
